field: 6887f96e-ee16-4b11-9a20-45e7c13aeda4 # FAQs
fieldLayouts:
  fd7744a6-631e-4c71-85de-f69e8ed104ba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 11d2fbd0-367e-4709-b5a0-ab8554cc5c29 # FAQ Question
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83112517-3c0b-4e93-ae8f-bcd601609e4d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fd99ba12-b360-4bbb-8fa1-2d576c0d95f5 # FAQ Answer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00be7e96-7df2-4e50-a43a-4a906bd20088
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 00256561-8b8e-4bd8-ac9e-715faec556a9
        userCondition: null
fields:
  11d2fbd0-367e-4709-b5a0-ab8554cc5c29: # FAQ Question
    columnSuffix: ovvqsihf
    contentColumnType: text
    fieldGroup: null
    handle: faqQuestion
    instructions: null
    name: 'FAQ Question'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  fd99ba12-b360-4bbb-8fa1-2d576c0d95f5: # FAQ Answer
    columnSuffix: dtcriruu
    contentColumnType: text
    fieldGroup: null
    handle: faqAnswer
    instructions: null
    name: 'FAQ Answer'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: faqItem
name: 'FAQ Item'
sortOrder: 1
