field: f1dbd402-7281-4d1a-a2dc-3753d5a44df9 # Company Bullets
fieldLayouts:
  009e313f-008c-4d35-86cf-337c07d0463b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 089201a8-2f54-4061-8689-d946689afe52 # Bullet Head
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90119fa0-8a65-4ed4-9332-a7e739ca72ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: be094951-a83c-4f73-90e2-1279b3332b1b # Bullet Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c805a461-7249-4a59-a523-d6c6263c1609
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1432a834-0d20-48cb-8eb0-52beaa8e92ff
        userCondition: null
fields:
  089201a8-2f54-4061-8689-d946689afe52: # Bullet Head
    columnSuffix: vexgxqne
    contentColumnType: text
    fieldGroup: null
    handle: homeCompanyBulletHead
    instructions: null
    name: 'Bullet Head'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  be094951-a83c-4f73-90e2-1279b3332b1b: # Bullet Copy
    columnSuffix: ddmkszbd
    contentColumnType: text
    fieldGroup: null
    handle: homeCompanyBulletCopy
    instructions: null
    name: 'Bullet Copy'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: homeCompanyBullet
name: Bullet
sortOrder: 1
