columnSuffix: null
contentColumnType: string
fieldGroup: 24552ad8-1522-4671-bd6f-aefad369b0ef # About MB
handle: aboutMbSidebarAccordion
instructions: null
name: 'Sidebar Accordion'
searchable: false
settings:
  contentTable: '{{%matrixcontent_aboutmbsidebaraccordion}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
