columnSuffix: fhjnjazi
contentColumnType: text
fieldGroup: 5f0332ac-8ba6-4aab-ab82-e982da9d4551 # Posts
handle: postContent
instructions: null
name: Content
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - 14a6f0f3-b531-4d1d-a2b5-c9b0a56a2ef0 # Assets
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: Post.json
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
