dateModified: 1679093910
email:
  fromEmail: alhmail@gmail.com
  fromName: 'Modern Body'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  imageFiles:
    hasUrls: true
    name: 'Image Files'
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
  videoFiles:
    hasUrls: true
    name: 'Video Files'
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
meta:
  __names__:
    0abc2601-eb4e-47a7-bb20-6358900e5ed0: 'About Image' # About Image
    0d0100be-ea79-4a84-b7ba-2a406203ef77: 'Company Image' # Company Image
    5d6e6468-5ba1-4d69-9cc9-61ae8d7dec0c: 'Testimonial Image' # Testimonial Image
    6bfbcd2b-1df4-4957-93f9-af5634cb74d7: 'Product Link' # Product Link
    6d8edb5f-1775-4b83-9df0-2c1fb6d97ae7: Videos # Videos
    6dd9aa0b-b4f3-4320-8d34-181a52eb6a00: Home # Home
    07dede5f-e375-4ca2-9622-0adde621a5c3: Home # Home
    8fcc0341-0be2-48bb-867d-c746a78e9c82: 'Products Items' # Products Items
    9a08632a-f16d-4a7b-98d7-ded85bf94df6: Images # Images
    9d74e71c-d037-432d-887d-4065ec79a9c7: 'Modern Body' # Modern Body
    21b6ca88-6ace-44d7-8c0e-fb6ccbab53d8: Bullet # Bullet
    34d91206-bdc7-4cac-b810-e54fa52a8f98: 'Products Head' # Products Head
    43c4b11f-16f2-4fb5-8984-7701e5e667d0: 'Hero Tagline' # Hero Tagline
    63ee439f-a7aa-41cf-b686-93b2f5f6392d: 'Product Link Text' # Product Link Text
    96f6e380-8739-4368-a5b3-042e778befe7: 'Company Head' # Company Head
    196bdac8-d7ed-4635-acc3-e671ce97f550: Common # Common
    9121f0f4-c29a-4085-af84-e633b5d10a1a: Title # Title
    089201a8-2f54-4061-8689-d946689afe52: 'Bullet Head' # Bullet Head
    bc2faaee-59b6-4f7a-a9a5-36f7a19cbb14: 'Products List' # Products List
    be094951-a83c-4f73-90e2-1279b3332b1b: 'Bullet Copy' # Bullet Copy
    bfc66a87-43b5-45fb-992a-27586fcff3e4: 'Testimonials Head' # Testimonials Head
    c249f4db-294d-44b8-ba21-a84bc989d17a: Home # Home
    c422089c-49f0-4d9a-9b30-dca485b14661: 'Hero Video' # Hero Video
    ca38367d-589e-4287-bdc0-29124c535643: 'Company Copy' # Company Copy
    d7efe282-0770-409c-b80d-98a2d44f3231: 'Testimonials List' # Testimonials List
    d76015ab-cb69-4d6c-9f18-cc3506db7bd7: 'Testimonial Name' # Testimonial Name
    da4444f1-47dd-462a-84b6-0d72b5c266f6: 'Product Title' # Product Title
    da521950-25a7-4aaa-be24-0f045a90984a: 'Product Description' # Product Description
    e86c3ea3-5a1e-4917-a91a-cee28bdf3ca3: 'About Copy' # About Copy
    e89c1ecc-9442-423f-ab32-6b3d2de27eac: 'Hero Logo' # Hero Logo
    ebe89201-1375-4202-8c7d-80cd9a140f5d: Testimonial # Testimonial
    edd1d7a7-ee00-446d-af3c-31d47d1609b4: 'Modern Body' # Modern Body
    f1dbd402-7281-4d1a-a2dc-3753d5a44df9: 'Company Bullets' # Company Bullets
    f4af40b0-3ee1-4b65-bfe3-fcf6e67c3c75: 'About Signature' # About Signature
    f851a4be-7bd7-4309-b0ef-c6ae24caecf3: 'Testimonial Items' # Testimonial Items
plugins:
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      assetPath: /assets
      publicPath: /
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
system:
  edition: solo
  live: true
  name: 'Modern Body'
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
