dateModified: 1682220132
email:
  fromEmail: alhmail@gmail.com
  fromName: 'Modern Body'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      cdnUrlPattern: ''
      customSubfolder: ''
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: modern-body/local/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://cdn2.assets-servd.host'
meta:
  __names__:
    0abc2601-eb4e-47a7-bb20-6358900e5ed0: 'About Image' # About Image
    0d0100be-ea79-4a84-b7ba-2a406203ef77: 'Company Image' # Company Image
    0e24ebfd-5210-45ab-8434-b505aa1e3db4: Link # Link
    0e62c248-99e6-42ab-b8cd-d7ec668bc886: 'Hero Image' # Hero Image
    1f1a8a59-4979-401d-82a3-b9b53b9c1de2: Classes # Classes
    5c337995-e31f-4ea4-9ee5-80ee8beda0c9: Global # Global
    5d6e6468-5ba1-4d69-9cc9-61ae8d7dec0c: 'Testimonial Image' # Testimonial Image
    5d9037d9-870f-4c88-93fb-fc01efa9af9d: Subtitle # Subtitle
    6bfbcd2b-1df4-4957-93f9-af5634cb74d7: 'Product Link' # Product Link
    6dd9aa0b-b4f3-4320-8d34-181a52eb6a00: Home # Home
    07dede5f-e375-4ca2-9622-0adde621a5c3: Home # Home
    8fcc0341-0be2-48bb-867d-c746a78e9c82: 'Products Items' # Products Items
    9d74e71c-d037-432d-887d-4065ec79a9c7: 'Modern Body' # Modern Body
    010f0163-ae73-4856-aa58-73380990ab5b: Description # Description
    14a6f0f3-b531-4d1d-a2b5-c9b0a56a2ef0: Assets # Assets
    21b6ca88-6ace-44d7-8c0e-fb6ccbab53d8: Bullet # Bullet
    29c627bb-9663-43ab-95e0-dec6b1e20414: 'Main Nav' # Main Nav
    34d91206-bdc7-4cac-b810-e54fa52a8f98: 'Products Head' # Products Head
    43c4b11f-16f2-4fb5-8984-7701e5e667d0: 'Hero Tagline' # Hero Tagline
    63ee439f-a7aa-41cf-b686-93b2f5f6392d: 'Product Link Text' # Product Link Text
    84d4713f-9e53-4b1c-8d8e-e5600fa07269: Class # Class
    96f6e380-8739-4368-a5b3-042e778befe7: 'Company Head' # Company Head
    196bdac8-d7ed-4635-acc3-e671ce97f550: Common # Common
    221b0134-0f21-4270-a087-06a4eaf0ded3: About # About
    313c48a2-dfc1-4518-9ba6-7fc0974e9c50: Block # Block
    485c9d29-4e5b-4658-9c86-ed411faf38f6: Title # Title
    854bb4fe-e607-46c0-8623-93814869aea5: Description # Description
    949dacbe-f141-438a-9783-ccf2d76f4cc3: Full-Width # Full-Width
    9121f0f4-c29a-4085-af84-e633b5d10a1a: Title # Title
    83953fb7-e107-4565-970c-a90f8151ddd5: Classes # Classes
    089201a8-2f54-4061-8689-d946689afe52: 'Bullet Head' # Bullet Head
    476101d0-23c9-47fa-98eb-7d3ec4770862: Credentials # Credentials
    612978b4-b183-4027-a49c-607cf17f73f3: 'Full-Width Laptop' # Full-Width Laptop
    51560042-57cb-418c-8ba2-b86b090eb5b4: Title # Title
    92053381-bc29-48a8-b8c9-f691eefa64b5: Title # Title
    b87d114e-c463-4311-adbe-dc8e506e6d2b: Classes # Classes
    b87e3b3f-cace-45aa-9c6d-2378c7874b72: Image # Image
    bc2faaee-59b6-4f7a-a9a5-36f7a19cbb14: 'Products List' # Products List
    be094951-a83c-4f73-90e2-1279b3332b1b: 'Bullet Copy' # Bullet Copy
    bf710d01-d9f2-4c16-97d2-6e04c591a6cd: Image # Image
    bfc66a87-43b5-45fb-992a-27586fcff3e4: 'Testimonials Head' # Testimonials Head
    c3cb6ef7-7f2e-4185-84a3-704e84298417: 'Class List' # Class List
    c249f4db-294d-44b8-ba21-a84bc989d17a: Home # Home
    c45206d2-9d75-4bdb-9a7a-7871d6f93696: 'Logo Image Long' # Logo Image Long
    c422089c-49f0-4d9a-9b30-dca485b14661: 'Hero Video' # Hero Video
    ca38367d-589e-4287-bdc0-29124c535643: 'Company Copy' # Company Copy
    cb0bc08e-fc13-48d5-94d7-26e840daa2df: 'Logo Image' # Logo Image
    cdd37bfc-0c28-4258-91d1-7a6a000c53f6: Bio # Bio
    d7efe282-0770-409c-b80d-98a2d44f3231: 'Testimonials List' # Testimonials List
    d76015ab-cb69-4d6c-9f18-cc3506db7bd7: 'Testimonial Name' # Testimonial Name
    da4444f1-47dd-462a-84b6-0d72b5c266f6: 'Product Title' # Product Title
    da521950-25a7-4aaa-be24-0f045a90984a: 'Product Description' # Product Description
    dc20bdf1-05e5-46dd-a2a8-1e01886722ff: Global # Global
    e7ca93f7-a988-4c82-ac6e-51212c511d4f: About # About
    e81aaea7-81e6-4426-937a-9af062c0cd16: 'Credentials Head' # Credentials Head
    e86c3ea3-5a1e-4917-a91a-cee28bdf3ca3: 'About Copy' # About Copy
    e89c1ecc-9442-423f-ab32-6b3d2de27eac: 'Hero Logo' # Hero Logo
    ebe89201-1375-4202-8c7d-80cd9a140f5d: Testimonial # Testimonial
    ec6b8c17-c1c6-4f35-ad4c-eb15724fdc38: About # About
    edd1d7a7-ee00-446d-af3c-31d47d1609b4: 'Modern Body' # Modern Body
    ef78c8c4-5030-4480-8f50-50b231fff44c: 'Second Image' # Second Image
    f1dbd402-7281-4d1a-a2dc-3753d5a44df9: 'Company Bullets' # Company Bullets
    f4af40b0-3ee1-4b65-bfe3-fcf6e67c3c75: 'About Signature' # About Signature
    f8eb5410-e3fc-41c3-a94e-d80f41ebad14: 'Full-width Mobile' # Full-width Mobile
    f851a4be-7bd7-4309-b0ef-c6ae24caecf3: 'Testimonial Items' # Testimonial Items
plugins:
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      assetPath: /assets
      publicPath: /
  navigation:
    edition: standard
    enabled: true
    licenseKey: AHXYW4VZ3YUFHQ4EHMY9P8TD
    schemaVersion: 2.0.7
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      adjustFeedmeLogs: ''
      assetsEnvironment: ''
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: always
      disableDynamic: ''
      disableTransforms: ''
      fsMaps:
        __assoc__:
          -
            - imageFiles
            - none
          -
            - media
            - none
          -
            - videoFiles
            - none
      fsMapsEnabled: ''
      imageAutoConversion: webp
      injectCors: ''
      projectSlug: ''
      securityKey: ''
      suppressWarnings: ''
      useLocalVolumes: false
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
system:
  edition: solo
  live: true
  name: 'Modern Body'
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
