fieldLayouts:
  5adaffd7-b0ae-40e2-8593-c333041b818b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cb0bc08e-fc13-48d5-94d7-26e840daa2df # Logo Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9e967cd-a811-4f6c-b0a8-3f958242db1b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c45206d2-9d75-4bdb-9a7a-7871d6f93696 # Logo Image Long
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f463f536-0bf8-47eb-a920-967a2ce519fc
            userCondition: null
            warning: null
            width: 100
        name: Image
        uid: 37f5331c-13e1-4a5b-8db7-768488a143ff
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4d2ffb4a-b740-4fd6-96c8-451c18168856 # Tik Tok
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d26b378-8979-4f86-a956-033e82d94e32
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cef6c373-ddac-4750-a65b-14ec99b6a138 # YouTube
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f965f4cd-092f-435d-9d77-bf8dea7c4831
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 45cdf667-692c-4321-96aa-54465fc2c000 # Instagram
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a737bd4-843f-434d-8ec0-4bf48f97a3d4
            userCondition: null
            warning: null
            width: 100
        name: 'Social Media'
        uid: 3421dc66-f03d-4731-9d54-2be7dbf46f36
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ecb84e38-b859-4ef8-aeaa-c1e468b2fd35 # Newsletter Subscribe Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02ea93f6-da57-4640-aefd-a5aac1362913
            userCondition: null
            warning: null
            width: 100
        name: Newsletter
        uid: 429e79a9-6431-4b1e-a965-9977af7c52d1
        userCondition: null
handle: global
name: Global
sortOrder: 1
