defaultPlacement: end
enableVersioning: true
handle: aboutModernBody
name: 'About Modern Body'
propagationMethod: all
siteSettings:
  9d74e71c-d037-432d-887d-4065ec79a9c7: # Modern Body
    enabledByDefault: true
    hasUrls: true
    template: aboutMB/_entry.html
    uriFormat: about-modern-body
type: single
