defaultPlacement: end
enableVersioning: true
handle: aboutAly
name: 'About Aly'
propagationMethod: all
siteSettings:
  9d74e71c-d037-432d-887d-4065ec79a9c7: # Modern Body
    enabledByDefault: true
    hasUrls: true
    template: aboutAly/_entry
    uriFormat: about-aly
type: single
