defaultPlacement: end
enableVersioning: true
handle: classes
name: Classes
propagationMethod: all
siteSettings:
  9d74e71c-d037-432d-887d-4065ec79a9c7: # Modern Body
    enabledByDefault: true
    hasUrls: true
    template: classes/_entry.html
    uriFormat: classes
type: single
