defaultPlacement: end
enableVersioning: true
handle: introToPilates
name: 'Intro to Pilates'
propagationMethod: all
siteSettings:
  9d74e71c-d037-432d-887d-4065ec79a9c7: # Modern Body
    enabledByDefault: true
    hasUrls: true
    template: intro/_entry
    uriFormat: intro-to-pilates
type: single
