defaultPlacement: end
enableVersioning: true
handle: training
name: '1:1 Training'
propagationMethod: all
siteSettings:
  9d74e71c-d037-432d-887d-4065ec79a9c7: # Modern Body
    enabledByDefault: true
    hasUrls: true
    template: training/_entry
    uriFormat: training
type: single
